/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gamal;

import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author pbzs4n
 */
public class Inter extends javax.swing.JFrame {
    public BigInteger p, b, c, secretKey;
    public Random sc = new SecureRandom();
    public BigInteger brmodp;
    public List<BigInteger> ecMessage = new ArrayList<>();
    public String ecMsg;
    public String dcMsg;
    /**
     * Creates new form Inter
     */
    public Inter() {
        initComponents();
        p = BigInteger.probablePrime(64, sc);
        b = new BigInteger("3");
        ecMsg="";
        dcMsg="";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        windowTItle = new javax.swing.JLabel();
        inputDataPanel = new javax.swing.JPanel();
        secretKeyLabel = new javax.swing.JLabel();
        message = new javax.swing.JLabel();
        secretKeyTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageTextArea = new javax.swing.JTextArea();
        generateMsgBtn = new javax.swing.JButton();
        ecMessagePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        descifrarMessageBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ecMessageField = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        dcMessageField = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(53, 53, 53));
        mainPanel.setForeground(new java.awt.Color(255, 255, 255));

        windowTItle.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        windowTItle.setForeground(new java.awt.Color(255, 255, 255));
        windowTItle.setText("EL TAMAL");

        inputDataPanel.setBackground(new java.awt.Color(53, 53, 53));
        inputDataPanel.setPreferredSize(new java.awt.Dimension(250, 210));

        secretKeyLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        secretKeyLabel.setForeground(new java.awt.Color(255, 255, 255));
        secretKeyLabel.setText("Secret KEY:");

        message.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        message.setForeground(new java.awt.Color(255, 255, 255));
        message.setText("Mensaje:");

        secretKeyTextField.setToolTipText("Este campo debe ser un número.");
        secretKeyTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secretKeyTextFieldActionPerformed(evt);
            }
        });

        messageTextArea.setColumns(20);
        messageTextArea.setRows(5);
        jScrollPane1.setViewportView(messageTextArea);

        generateMsgBtn.setText("Cifrar mensaje");
        generateMsgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateMsgBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inputDataPanelLayout = new javax.swing.GroupLayout(inputDataPanel);
        inputDataPanel.setLayout(inputDataPanelLayout);
        inputDataPanelLayout.setHorizontalGroup(
            inputDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inputDataPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(generateMsgBtn)
                .addGap(76, 76, 76))
            .addGroup(inputDataPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addGroup(inputDataPanelLayout.createSequentialGroup()
                        .addGroup(inputDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(secretKeyLabel)
                            .addComponent(message))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(secretKeyTextField))
                .addContainerGap())
        );
        inputDataPanelLayout.setVerticalGroup(
            inputDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputDataPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(secretKeyLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(secretKeyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(message)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(generateMsgBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ecMessagePanel.setBackground(new java.awt.Color(53, 53, 53));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mensaje cifrado:");

        descifrarMessageBtn.setText("Descifrar mensaje");
        descifrarMessageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descifrarMessageBtnActionPerformed(evt);
            }
        });

        ecMessageField.setEditable(false);
        ecMessageField.setColumns(20);
        ecMessageField.setRows(5);
        jScrollPane2.setViewportView(ecMessageField);

        javax.swing.GroupLayout ecMessagePanelLayout = new javax.swing.GroupLayout(ecMessagePanel);
        ecMessagePanel.setLayout(ecMessagePanelLayout);
        ecMessagePanelLayout.setHorizontalGroup(
            ecMessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ecMessagePanelLayout.createSequentialGroup()
                .addGroup(ecMessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ecMessagePanelLayout.createSequentialGroup()
                        .addGroup(ecMessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ecMessagePanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1))
                            .addGroup(ecMessagePanelLayout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(descifrarMessageBtn)))
                        .addGap(0, 58, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        ecMessagePanelLayout.setVerticalGroup(
            ecMessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ecMessagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(descifrarMessageBtn)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(53, 53, 53));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mensaje descifrado:");

        dcMessageField.setEditable(false);
        dcMessageField.setColumns(20);
        dcMessageField.setRows(5);
        jScrollPane3.setViewportView(dcMessageField);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(inputDataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(ecMessagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(windowTItle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(windowTItle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ecMessagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputDataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generateMsgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateMsgBtnActionPerformed
        if (secretKeyTextField.getText()!= "" && messageTextArea.getText() != ""){
            ecMsg="";
            ecMessage.clear();
            try {
                secretKey = new BigInteger(secretKeyTextField.getText());
                c = b.modPow(secretKey, p);
                // Se toma el mensaje a cifrar
                String s = messageTextArea.getText();
                BigInteger r = new BigInteger(64, sc);
                byte[] bytes = s.getBytes("UTF-8");
                for( byte elem: bytes ){
                    int aux = elem;
                    String value = Integer.toString(aux);
                    BigInteger X = new BigInteger(value);
                    BigInteger EC = X.multiply(c.modPow(r, p)).mod(p);
                    ecMessage.add(EC);
                    ecMsg += EC.toString() + "\n";
                }
                ecMessageField.setText(ecMsg);
                brmodp = b.modPow(r, p);
            } catch (UnsupportedEncodingException ex) {
                Logger.getLogger(Inter.class.getName()).log(Level.SEVERE, null, ex);
            }
        }        
    }//GEN-LAST:event_generateMsgBtnActionPerformed

    private void descifrarMessageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descifrarMessageBtnActionPerformed
       
        if(!ecMessage.isEmpty()){
            dcMsg="";
            BigInteger crmodp = brmodp.modPow(secretKey, p);
            BigInteger d = crmodp.modInverse(p);
            List<BigInteger> dcMessage = new ArrayList<>();
            // descifrar cada byte cifrado
            for (BigInteger elem: ecMessage){
                BigInteger ad = d.multiply(elem).mod(p);
                dcMessage.add(ad);
            }
            // interpretar el valor ascii en caracteres
            for (BigInteger elem: dcMessage){
                int aux = Integer.parseInt(elem.toString());
                dcMsg += (char)aux;
            }
            dcMessageField.setText(dcMsg);
        }
    }//GEN-LAST:event_descifrarMessageBtnActionPerformed

    private void secretKeyTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secretKeyTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secretKeyTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea dcMessageField;
    private javax.swing.JButton descifrarMessageBtn;
    private javax.swing.JTextArea ecMessageField;
    private javax.swing.JPanel ecMessagePanel;
    private javax.swing.JButton generateMsgBtn;
    private javax.swing.JPanel inputDataPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel message;
    private javax.swing.JTextArea messageTextArea;
    private javax.swing.JLabel secretKeyLabel;
    private javax.swing.JTextField secretKeyTextField;
    private javax.swing.JLabel windowTItle;
    // End of variables declaration//GEN-END:variables
}
